server:
  port: 10010
spring:
  application:
    name: leyou-gateway
 # http:
  #  encoding:
   #   charset: utf-8
    #  force: true
     # enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/** #商品微服务的映射路径
    search-service: /search/** #搜索微服务的映射路径
    user-service: /user/** #用户微服务
    auth-service: /auth/** #授权中心微服务 #携带域名信息
    cart-service: /cart/** #购物车微服务
    order-service: /order/**  #订单服务
  add-host-header: true
  sensitive-headers: #配置禁止使用的 头信息
leyou:
  jwt:
    pubKeyPath: G:\miyao\rsa.pub #公钥地址
    cookieName: LY_TOKEN #cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/user/logout
      - /api/item
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
 # ignored-services:
  #  - upload-service #忽略文件上传的服务  可以配置多个