server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.26.129
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4FftKmrQ21zLe2tF6sjc
    accessKeySecret: Pl1mt2cgkELHUiQSmKF1NElJHXXtof
    signName: 油墩街人民 #签名名称
    verifyCodeTemplate: SMS_175405675 #模板名称