server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=utf8
    username: root
    password: dlt362330.
    hikari:
      max-lifetime: 28830000 #一个连接的生命时长（毫秒）  默认30分钟
      maximum-pool-size: 9 #连接池允许的最大连接数  默认10
  rabbitmq:
    host: 192.168.26.129
    username: leyou
    password: leyou
    virtual-host: /leyou
    template: #有关AmqpTemplate的配置
      exchange: leyou.item.exchange #缺省的交换机名称
    publisher-confirms: true #生产者确认机制，确保消息会正常发送 ，如果发送失败会有错误回执，从而触发重试
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳发送时间间隔
    lease-expiration-duration-in-seconds: 10 #10秒不发送就过期

